apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubernetes-webhook.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-webhook.selectorLabels" . | nindent 8 }}
webhooks:
  - name: mutating-example.dev.com
    clientConfig:
      service:
        name: {{ include "kubernetes-webhook.serviceAccountName" . }}
        namespace: default
        path: "/mutate"
      caBundle: "{{ .Values.caBundle }}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
