apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-webhook.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - qikqiak.com
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
      - certificates.k8s.io
      - ""
      - "*"
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - certificatesigningrequests
      - certificate
      - secret
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'
