apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubernetes-webhook.serviceAccountName" . }}
  labels:
    {{- include "kubernetes-webhook.selectorLabels" . | nindent 8 }}
webhooks:
  - name: required-labels.dev.com
    clientConfig:
      service:
        name: {{ include "kubernetes-webhook.serviceAccountName" . }}
        namespace: default
        path: "/validate"
      caBundle: "{{ .Values.caBundle }}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

